CREATE TABLE USER (
	ID BIGINT(20) NOT NULL AUTO_INCREMENT,
	NOMBRE VARCHAR(50) NOT NULL,
	PASSWORD VARCHAR(100) NOT NULL,
	ENABLED CHAR(1) NOT NULL DEFAULT 'Y',
	PRIMARY KEY (ID) USING BTREE,
	UNIQUE INDEX NAME_USER_UNIQUE (NOMBRE) USING BTREE
);

ALTER TABLE USER ADD CONSTRAINT ENABLED_USER_CHECK CHECK (ENABLED = 'Y' OR ENABLED = 'N');

INSERT INTO USER (NOMBRE, PASSWORD) VALUES ("ADMIN", "QUU4NDFBVw==");

CREATE TABLE ROL (
	ID BIGINT(20) NOT NULL AUTO_INCREMENT,
	NOMBRE VARCHAR(50) NOT NULL,
	ENABLED CHAR(1) NOT NULL DEFAULT 'Y',
	PRIMARY KEY (ID) USING BTREE,
	UNIQUE INDEX NAME_ROL_UNIQUE (NOMBRE) USING BTREE
);

ALTER TABLE ROL ADD CONSTRAINT ENABLED_ROL_CHECK CHECK (ENABLED = 'Y' OR ENABLED = 'N');

INSERT INTO ROL (NOMBRE) VALUES ("ADMIN");

CREATE TABLE USER_ROL_REL (
  	ID BIGINT(20) NOT NULL AUTO_INCREMENT,
	USER_ID BIGINT(20) NOT NULL,
	ROL_ID BIGINT(20) NOT NULL,
	PRIMARY KEY (ID),
	CONSTRAINT FK__user FOREIGN KEY (USER_ID) REFERENCES USER (ID) ON UPDATE RESTRICT ON DELETE RESTRICT,
	CONSTRAINT FK__rol FOREIGN KEY (ROL_ID) REFERENCES ROL (ID) ON UPDATE RESTRICT ON DELETE RESTRICT
);

INSERT INTO USER_ROL_REL (USER_ID, ROL_ID)
       VALUES ((SELECT ID
                  FROM USER
                  WHERE NOMBRE = 'ADMIN'),
               (SELECT ID
                  FROM ROL
                  WHERE NOMBRE = 'ADMIN'));
